---
name: Version
on:
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  name: Version
  runs-on: ubuntu-latest
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install npm@latest
      run: npm install npm@latest -g
    - name: npm Version
      run: npm -v
